minimum_pre_commit_version: 2.13.0
default_stages: [ commit, push ]
exclude: '^$'
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace